games:
    - class: steam_app_
      name: Steam Games
      prefix: true
      use_title: true
    - class: hl2_linux
      name: Half-Life 2
    - class: RimWorldLinux
      name: RimWorld
    - class: FishingPlanet.X86_64
      name: Fishing Planet
    - class: rocketleague
      name: Rocket League
      prefix: true
    - class: BeamNG.drive.x64
      name: BeamNG.drive
    - class: Minecraft
      name: Minecraft
      prefix: true
settings:
    notifications: true
    log_sessions: true
    sessions_file: /home/austincgause/.local/share/gametrak/sessions.jsonl
    hyprland_conf: /home/austincgause/.config/gametrak/games.conf
    min_session_mins: 15
