# Topgrade Configuration
# See: https://github.com/topgrade-rs/topgrade/wiki
# Example config: https://github.com/topgrade-rs/topgrade/blob/main/config.example.toml

[misc]
# Run `sudo -v` to cache credentials at the start of the run
# This avoids a blocking password prompt in the middle of an unattended run
# (default: false)
pre_sudo = true

# Disable specific steps - same options as the command line flag
disable = ["gcloud", "self_update"]

# Display the time in step titles (default: true)
display_time = true

# Don't ask for confirmations (no default value)
assume_yes = true

# Cleanup temporary or old files after updates
cleanup = true



[linux]
## Arch Package Manager to use.
# Allowed values:
#   autodetect, aura, garuda_update, pacman, pamac, paru, pikaur, trizen, yay
arch_package_manager = "yay"

# Show Arch news before updating (recommended!)
show_arch_news = true



[git]
# Max number of git repos to update in parallel
max_concurrency = 5



[npm]
# Use sudo if NPM directory isn't owned by current user
# Usually not needed if using nvm
use_sudo = false



[flatpak]
# Use sudo for system-wide flatpak updates
use_sudo = true



[commands]
"Mason Update" = "nvim --headless -c \"lua require('lazy').load({plugins = {'mason-tool-installer.nvim'}})\" -c 'autocmd User MasonToolsUpdateCompleted quitall' -c 'MasonToolsUpdate'"
