[mgr]
prepend_keymap = [
    
    # plugin keybinds
    { on = [ "c", "m" ], run = "plugin chmod",              desc = "Chmod on selected files" },
    { on = [ "c", "c" ], run = "plugin copy-file-contents", desc = "Copy file contents to clipboard" },

    # TODO: add additional g key mappings for quick directory jumping
    # directory nav
    { on = [ "g", "d", "t" ], run = "cd ~/.dotfiles",   desc = "cd Dots"  },
    { on = [ "g", "d", "c" ], run = "cd ~/Documents",   desc = "cd Docs"  },
    { on = [ "g", "d", "w" ], run = "cd ~/Downloads",   desc = "cd Down"  },
    { on = [ "g", "c" ],      run = "cd ~/Cloud",       desc = "cd Cloud" },
    { on = [ "g", "n" ],      run = "cd ~/Cloud/Notes", desc = "cd Notes" },
    { on = [ "g", "j" ],      run = "cd ~/Cloud/JD",    desc = "cd JDex"  },
    { on = [ "g", "a" ],      run = "cd '~/Cloud/JD/30-39 Academia/34 Undergrad (BS CS) (VSU)'", desc = "cd Academia"  },

]
