[mgr]
prepend_keymap = [
    
    # plugin keybinds
    { on = [ "c", "m" ], run = "plugin chmod",              desc = "Chmod on selected files" },
    { on = [ "c", "c" ], run = "plugin copy-file-contents", desc = "Copy file contents to clipboard" },

    # TODO: add additional g key mappings for quick directory jumping
    # directory nav
    { on = [ "g", "d" ], run = "cd ~/.dotfiles", desc = "cd Dots" },
    { on = [ "g", "c" ], run = "cd ~/Cloud/",    desc = "cd Cloud" },
    { on = [ "g", "n" ], run = "cd ~/Notes/",    desc = "cd Notes" },
    { on = [ "g", "j" ], run = "cd ~/JDex/",     desc = "cd JDex" },
    # { on = [ "g", "j" ], run = "cd '~/MEGA/00-09 System/00 System Management/00.00 JDex/'",   desc = "cd JDex" },

]
