scan_dirs:
    - path: ~/.dotfiles/dot_config
      alias: "Config"
    - path: ~/Dev
    - path: ~/Dev/CS-Homework/
entry_dirs:
    - ~/.dotfiles
    - ~/Documents
    - ~/Downloads
    - ~/Cloud
ignore_dirs:
    - ~/Dev/_practice
    - ~/Dev/_archive
    - ~/Dev/CS-Homework/
session_layout:
    windows:
        - cmd: nvim
          name: edit
        - cmd: ""
          name: term
fallback_session:
    layout:
        windows:
            - cmd: ""
              name: window
    name: Default
    path: ~/
settings:
    always_kill_on_last_session: true
    default_depth: 1
    editor: nvim
    tmux_base: 1
    tmux_session_prefix: '[TMUX] '
